from .combat import OSNRCombat
from .fishing import OSNRFishing
from .mining import OSNRMining
from .osnr_bot import OSNRBot
from .runecraft_astral import OSNRAstralRunes
from .snape_grass import OSNRSnapeGrass
from .thieving_pickpocket import OSNRThievingPickpocket
from .thieving_stall import OSNRThievingStall
from .woodcutting import OSNRWoodcutting